name: API Tests

on:
  push:
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # 1️: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2: Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # 4: Create a directory for test results
      - name: Create Result Directory
        run: mkdir -p reports

      # 5: Run API tests
      - name: Run API Tests
        run: npm run afrToken-test

      # 6: Upload test result as an artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: RunReports
          path: reports